import type { NavItem } from "@/components/shell/Sidebar";

export const NAV: Record<string, NavItem[]> = {
  superadmin: [
    {
      title: 'Dashboard',
      href: '/super-admin/dashboard',
      icon: 'layout-dashboard'
    },
    { label: "Mapa Interativo", href: "/super-admin/mapa", icon: "map" },
    { label: "Mapa Real", href: "/super-admin/mapa-real", icon: "map-pin" },
    { label: 'Gestão de Filiais', href: '/super-admin/filiais', icon: 'building' },
    { label: 'Filiais Internas Cadastradas', href: '/super-admin/filiais-internas', icon: 'building' },
    { label: 'Gestão SaaS', href: '/super-admin/clientes-saas', icon: 'users' },
    { label: "Acessos por Filial", href: "/super-admin/filiais-acessos", icon: "shield" },
    {
      title: 'Contas Admin Filiais',
      href: '/super-admin/admins-filiais',
      icon: 'users'
    },
    { label: "Organizações", href: "/super-admin/organizacoes", icon: "building" },
    { label: "Usuários", href: "/super-admin/usuarios", icon: "user" },
    { label: "Aprovação", href: "/super-admin/aprovacao", icon: "check-circle" },
    { label: "Tokenização", href: "/super-admin/tokenizacao", icon: "key" },
    { label: "Contratos", href: "/super-admin/contratos", icon: "file-text" },
    { label: "Auditoria", href: "/super-admin/auditoria", icon: "file-text" },
    { label: "Widget Telemetry", href: "/super-admin/widget-telemetry", icon: "chart" },
    { label: "Inadimplência", href: "/super-admin/inadimplencia", icon: "chart" },
    { label: "Relatórios", href: "/super-admin/relatorios", icon: "bar-chart-2" },
    { label: "Configurações", href: "/super-admin/config", icon: "settings" },
  ],
  adminfilial: [
    { label: "Home", href: "/admin-filial", icon: "layout", panelKey: "adminfilial" },
    { label: "Equipe", href: "/admin-filial/equipe", icon: "users", panelKey: "adminfilial" },
    { label: "Empreendimentos", href: "/admin-filial/empreendimentos", icon: "building-2", panelKey: "adminfilial" },
    { label: "Novo Empreendimento", href: "/admin-filial/empreendimentos/novo", icon: "plus-circle", panelKey: "adminfilial" },
    { label: "Mapa", href: "/admin-filial/mapa", icon: "map", panelKey: "urbanista" },
    { label: "Mapa Interativo", href: "/admin-filial/mapa-interativo", icon: "map", panelKey: "urbanista" },
    { label: "Lotes", href: "/admin-filial/lotes", icon: "map-pin", panelKey: "adminfilial" },
    { label: "Vendas de Lotes", href: "/admin-filial/lotes-vendas", icon: "dollar-sign", panelKey: "comercial" },
    { label: "Nova Venda", href: "/admin-filial/vendas/novo", icon: "plus-circle", panelKey: "comercial" },
    { label: "Comissões", href: "/admin-filial/comissoes", icon: "dollar-sign", panelKey: "comercial" },
    { label: "Assinaturas", href: "/admin-filial/assinaturas", icon: "pen-line", panelKey: "adminfilial" },
    { label: "Auditoria", href: "/admin-filial/auditoria", icon: "file-text", panelKey: "adminfilial" },
    { label: "Relatórios", href: "/admin-filial/relatorios", icon: "chart", panelKey: "adminfilial" },
    { label: "Configurações", href: "/admin-filial/config", icon: "settings", panelKey: "adminfilial" },
  ],
  urbanista: [
    { title: "Urbanista", href: "/urbanista", icon: "map" },
    { label: "Relatórios", href: "/urbanista/relatorios", icon: "chart" },
    { label: "Configurações", href: "/urbanista/config", icon: "settings" },
    { label: "Mapas", href: "/urbanista/mapas", icon: "map" },
    { label: "Projetos", href: "/urbanista/projetos", icon: "briefcase" },
  ],
  juridico: [
    { title: "Jurídico", href: "/juridico", icon: "scroll-text" },
    { label: "Relatórios", href: "/juridico/relatorios", icon: "chart" },
    { label: "Configurações", href: "/juridico/config", icon: "settings" },
    { label: "Contratos", href: "/juridico/contratos", icon: "file" },
    { label: "Processos", href: "/juridico/processos", icon: "file" },
    { label: "Renegociações", href: "/juridico/renegociacoes", icon: "dollar-sign" },
  ],
  contabilidade: [
    { title: "Contabilidade", href: "/contabilidade", icon: "calculator" },
    { label: "Relatórios", href: "/contabilidade/relatorios", icon: "chart" },
    { label: "Configurações", href: "/contabilidade/config", icon: "settings" },
    { label: "Financeiro", href: "/contabilidade/financeiro", icon: "dollar-sign" },
    { label: "Fiscal", href: "/contabilidade/fiscal", icon: "file" },
  ],
  marketing: [
    { title: "Marketing", href: "/marketing", icon: "megaphone" },
    { label: "Relatórios", href: "/marketing/relatorios", icon: "chart" },
    { label: "Configurações", href: "/marketing/config", icon: "settings" },
    { label: "Campanhas", href: "/marketing/campanhas", icon: "briefcase" },
    { label: "Materiais", href: "/marketing/materiais", icon: "file" },
  ],
  comercial: [
    { title: "Comercial", href: "/comercial", icon: "briefcase" },
    { label: "Relatórios", href: "/comercial/relatorios", icon: "chart" },
    { label: "Configurações", href: "/comercial/config", icon: "settings" },
    { label: "Leads", href: "/comercial/leads", icon: "users" },
    { label: "Propostas", href: "/comercial/propostas", icon: "file" },
    { label: "Nova Venda", href: "/comercial/vendas/nova", icon: "plus-circle" },
    { label: "Cobranças", href: "/comercial/cobrancas", icon: "dollar-sign" },
    { label: "Comissões", href: "/comercial/comissoes", icon: "dollar-sign" },
  ],
  imobiliaria: [
    { title: "Imobiliária", href: "/imobiliaria", icon: "home" },
    { label: "Relatórios", href: "/imobiliaria/relatorios", icon: "chart" },
    { label: "Configurações", href: "/imobiliaria/config", icon: "settings" },
    { label: "Corretores", href: "/imobiliaria/corretores", icon: "users" },
    { label: "Leads", href: "/imobiliaria/leads", icon: "users" },
  ],
  corretor: [
    { title: "Corretor", href: "/corretor", icon: "user" },
    { label: "Relatórios", href: "/corretor/relatorios", icon: "chart" },
    { label: "Configurações", href: "/corretor/config", icon: "settings" },
    { label: "Leads", href: "/corretor/leads", icon: "users" },
    { label: "Vendas", href: "/corretor/vendas", icon: "dollar-sign" },
  ],
  obras: [
    { title: "Obras", href: "/obras", icon: "hammer" },
    { label: "Relatórios", href: "/obras/relatorios", icon: "chart" },
    { label: "Configurações", href: "/obras/config", icon: "settings" },
    { label: "Cronograma", href: "/obras/cronograma", icon: "calendar" },
    { label: "Andamento", href: "/obras/andamento", icon: "file" },
  ],
  investidor: [
    { title: "Investidor", href: "/investidor", icon: "line-chart" },
    { label: "Relatórios", href: "/investidor/relatorios", icon: "chart" },
    { label: "Configurações", href: "/investidor/config", icon: "settings" },
    { label: "Extratos", href: "/investidor/extratos", icon: "file-text" },
    { label: "Cobranças", href: "/investidor/cobrancas", icon: "dollar-sign" },
    { label: "Carteira", href: "/investidor/carteira", icon: "briefcase" },
    { label: "Suporte", href: "/investidor/suporte", icon: "inbox" },
  ],
  terrenista: [
    { title: "Terrenista", href: "/terrenista", icon: "landmark" },
    { label: "Relatórios", href: "/terrenista/relatorios", icon: "chart" },
    { label: "Configurações", href: "/terrenista/config", icon: "settings" },
    { title: "Extratos", href: "/terrenista/extratos", icon: "file-text" },
    { label: "Status", href: "/terrenista/status", icon: "check-circle" },
    { label: "Pagamentos", href: "/terrenista/pagamentos", icon: "dollar-sign" },
  ],
};

export function inferMenuKey(pathname: string) {
  const key = (pathname.split("/")[1] || "adminfilial").toLowerCase();
  return key;
}
